server:
  port: 9002
spring:
  application:
    name: player-ui
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC&useSSL=false
      username: root
      password: root
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

