server:
  port: 9001
spring:
  application:
    name: player-provider
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&serverTimeZone=UTC&useSSL=false
      username: root
      password: root
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.goodscommons.pojo
#指定当前服务注册的‘服务注册发现中心’的地址
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

